function sethdata = importMTdata(varargin)
%%
%
% Modified by swe from script for importing data from the following text file:
%
%    /Users/swe/Downloads/sethdata (1).csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.
%
% Format for textscan:
%   column1: categorical (%C)
%	column2: double (%f)
%   column3: double (%f)
%	column4: categorical (%C)
%   column5: text (%q)
% For more information, see the TEXTSCAN documentation.
%
% Auto-generated by MATLAB on 2021/08/23 10:51:28
%
%
%%

%% Parse input
Parser = inputParser;

addParameter(Parser,'filename','sethdata (1).csv')
addParameter(Parser,'delimiter',',')
addParameter(Parser,'startRow',2)
addParameter(Parser,'formatSpec','%C%f%f%C%q%[^\n\r]')

parse(Parser,varargin{:})

filename = Parser.Results.filename;
delimiter = Parser.Results.delimiter;
startRow = Parser.Results.startRow;
formatSpec = Parser.Results.formatSpec;

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, ...
    'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, ...
    'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
sethdata = table(dataArray{1:end-1}, 'VariableNames', {'neuron','coh','speed','prefdir','bins'});
